name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            registry: ${{secrets.DOCKER_URL}}
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/demo_CI:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKER_USERNAME}}/demo_CI:latest
